# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list
namespace: ns
resources:
- ../../pr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: app
images:
- name: nginx
  newTag: 1.16.1
patches:
- path: ingress.yaml
  target:
    kind: Ingress
    name: nginx-ingress